### ISSUE TITLE
please include LICENSE.txt in the sources uploaded to crates.io

### ISSUE THREAD

**Issue by decathorpe** [myrrlyn/funty#1]
There exist more than 20 variants of *the* "MIT" license.

Side note: Unless I did my comparison wrong, you seem to have chosen the "Modern Style with sublicense", as it is classified by the Fedora project: https://fedoraproject.org/wiki/Licensing:MIT?rd=Licensing/MIT#Modern_Style_with_sublicense

Your LICENSE.txt text states:

> The above copyright notice and this permission notice shall be included
> in all copies or substantial portions of the Software.

So, to clarify which "MIT" license actually applies, and to adhere to the text of the chosen license, please include the LICENSE.txt file with the crate published to crates.io. Adding a "LICENSE.txt" entry to the "include" array in Cargo.toml should do that.

**Comment by myrrlyn** [comment]
Closed in 4f259e0, will be present in the next publish. Thanks!
